version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3001:3001"
    networks:
      - map-app
  api-server:
    image: api-server
    ports:
      - "3006:3006"
    networks:
      - map-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27019:27017"
    networks:
      - map-app
    volumes:
      - mongo-data:/data/db
networks:
  map-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local